#!/bin/bash

CONFIG_PATH="$HOME/.config"
# Common
COMMON_PATH="$CONFIG_PATH/common"
COMMON_UTILS_PATH="$COMMON_PATH/utils"
COMMON_SCRIPTS_PATH="$COMMON_PATH/scripts"

# Zsh
ZSH_CONFIG_PATH="$CONFIG_PATH/zsh"